### PR TITLE
Nested metadata splitters

### PR DESCRIPTION
**Pull request by vepkenez**

### CODE REVIEW

**Comment by jMyles** [comment]
From Discord:

AM] jMyles: At first blush, this seems reasonable
[10:58 AM] jMyles: When do you suppose that these lengths will be used (by users of BSS, I mean).  In other words: what does the length of a (for example) ChecksumVerifyingSplitter mean to them?
[10:58 AM] jMyles: One thing I don't like about it: if the question is, "why I cast-and-append this, how many bytes will it occupy in my payload?" - it gives the wrong answer.
[11:11 AM] kprasch: This assertion shows show clean to compare can look now - without any special handling https://github.com/nucypher/bytestringSplitter/pull/33/files#diff-6c0b8eda6e69baae4b3b68f649a626b7R296
[11:12 AM] kprasch: It at least partially depends on how `__len__` is evaluated in nucypher under the hood
[11:13 AM] kprasch: Analternate approach might be to have methods for evaluating length
[11:20 AM] jMyles: I get it, I get it.  And as I say, it seems sensible.

But ultimately the question is: what are users likely to expect here?

Are they likely to expect that the "discharge" is the measurement being conducted by len?  Or the actual bytes representation of the object they have in hand?
[11:21 AM] jMyles: Typically, if I have an object (that is not a collection), `foo`, of type `Foo`, I expect that if `len(foo) == x`, then `len(bytes(foo)) == x` will hold as well.
[11:21 AM] jMyles: Let's bring it over to the PR
[11:21 AM] damonC: I kinda feel like the stuff we are adding for versioning and checksuming is "headers"
[11:21 AM] damonC: ok

**Comment by vepkenez** [comment]
@jMyles said this
> One thing I don't like about it: if the question is, "why I cast-and-append this, how many bytes will it occupy in my payload?" - it gives the wrong answer.

This is a good point.

@KPrasch you're right, maybe to deal with this we can just have a `def total_length`

**Comment by vepkenez** [comment]
I found that the use of `__len__` internally was causing me some headaches in that sometimes I want the bytes length and other times the payload length, and so i had to do stuff like [this](https://github.com/nucypher/bytestringSplitter/pull/33/files#diff-5d95d433d5749650ec9afb8d86e4c5e5R159)

**Comment by jMyles** [comment]
Or `length_without_headers` ?

**Comment by vepkenez** [comment]
right.

So... should `len(a_splitter_class)` be the length we should expect as bytes?
To be fair, one reason I didn't go that way is that if there's a VariableLength included in the splitter, what's the point anyway?

**Pull request closed without merging**
