### PR TITLE
 Fix computation of max length allowed for VariableLengthBytestring

### PR DESCRIPTION
**Pull request by cygnusv**

### CODE REVIEW

**Comment by jMyles** [comment]
Seems like a teachable moment - why is it 128 times larger than I thought?

**Comment by cygnusv** [comment]
BSS allows variable length messages, as long as their length can be encoded in `L` bytes (currently, `L=4`). `L` bytes allow to encode `2**(8 * L)` different values, which is equivalent to `256 ** L` values. Hence, variable length messages in BSS are limited to `256 ** L - 1` bytes.

**Comment by jMyles** [comment]
....yyyeah.  Sounds right.  Thanks! :-)

**Review by jMyles — APPROVED** [review]

**Review by michwill — APPROVED** [review]
Huh!

**Pull request merged**
